from typing import Any, Dict, Optional, Protocol

class Logger(Protocol):
    def debug(self, message: str, context: Optional[Dict[str, Any]] = None) -> None: ...
    def info(self, message: str, context: Optional[Dict[str, Any]] = None) -> None: ...
    def warn(self, message: str, context: Optional[Dict[str, Any]] = None) -> None: ...
    def error(self, message: str, error: Optional[Exception] = None, context: Optional[Dict[str, Any]] = None) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
