package com.digitalt3.commons.sdk;

import com.digitalt3.commons.api.LogEvent;
import com.digitalt3.commons.api.LogTransport;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Synchronously POSTs final DT3 structured events as JSON to an HTTP endpoint.
 *
 * <p>This transport receives events only after logger masking and validation.
 * It treats only 2xx responses as successful delivery and never includes event
 * content or response bodies in reported failures.</p>
 *
 * @since 0.1.0
 */
public final class HttpTransport implements LogTransport {

    private final URI endpoint;
    private final Duration timeout;
    private final Map<String, String> headers;
    private final HttpClient client;

    /**
     * Create a synchronous HTTP event transport.
     *
     * @param endpoint destination HTTP or HTTPS URL
     * @param timeoutMillis request timeout in milliseconds
     * @param headers optional request headers
     * @throws IllegalArgumentException if configuration is invalid
     */
    public HttpTransport(String endpoint, long timeoutMillis, Map<String, String> headers) {
        this.endpoint = parseEndpoint(endpoint);
        if (timeoutMillis <= 0) {
            throw new IllegalArgumentException(
                "exporter.http.timeout must be greater than zero"
            );
        }

        this.timeout = Duration.ofMillis(timeoutMillis);
        this.headers = validateHeaders(headers);
        this.client = HttpClient.newBuilder()
            .connectTimeout(this.timeout)
            .build();
    }

    /**
     * Create a synchronous HTTP event transport with a five-second timeout.
     *
     * @param endpoint destination HTTP or HTTPS URL
     * @param headers optional request headers
     */
    public HttpTransport(String endpoint, Map<String, String> headers) {
        this(endpoint, 5000, headers);
    }

    // PUBLIC_INTERFACE
    /**
     * Serialize and synchronously POST one final canonical structured event.
     *
     * @param logEvent already-masked and validation-processed event
     * @throws HttpTransportError when delivery fails, times out, or receives a non-2xx response
     */
    @Override
    public synchronized void write(LogEvent logEvent) {
        Objects.requireNonNull(logEvent, "logEvent must not be null");
        writeJson(StdoutLogger.toJson(logEvent.toMap()));
    }

    /**
     * Synchronously POST a serialized event generated by the logger pipeline.
     *
     * @param serializedEvent final canonical JSON event
     * @throws HttpTransportError when delivery fails, times out, or receives a non-2xx response
     */
    synchronized void writeJson(String serializedEvent) {
        Objects.requireNonNull(serializedEvent, "serializedEvent must not be null");

        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()
            .uri(endpoint)
            .timeout(timeout)
            .header("Content-Type", "application/json")
            .POST(HttpRequest.BodyPublishers.ofString(serializedEvent));

        for (Map.Entry<String, String> header : headers.entrySet()) {
            if (!"content-type".equalsIgnoreCase(header.getKey())) {
                requestBuilder.header(header.getKey(), header.getValue());
            }
        }

        try {
            HttpResponse<Void> response = client.send(
                requestBuilder.build(),
                HttpResponse.BodyHandlers.discarding()
            );
            int status = response.statusCode();
            if (status < 200 || status >= 300) {
                throw new HttpTransportError("HTTP export failed with status " + status);
            }
        } catch (java.net.http.HttpTimeoutException exception) {
            throw new HttpTransportError("HTTP export request timed out", exception);
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new HttpTransportError("HTTP export request interrupted", exception);
        } catch (IOException exception) {
            throw new HttpTransportError("HTTP export request failed", exception);
        }
    }

    // PUBLIC_INTERFACE
    /**
     * Flush the synchronous HTTP transport.
     *
     * <p>Every request completes before {@link #write(LogEvent)} returns, so no
     * buffered events remain to flush.</p>
     */
    @Override
    public void flush() {
        // No-op: HttpClient.send completes synchronously.
    }

    // PUBLIC_INTERFACE
    /**
     * Shut down this HTTP transport.
     *
     * <p>The standard Java HTTP client owns no closeable resources exposed by
     * this transport, so shutdown has no additional work.</p>
     */
    @Override
    public void shutdown() {
        // No-op: HttpClient has no explicit shutdown operation in Java 17.
    }

    private URI parseEndpoint(String configuredEndpoint) {
        if (configuredEndpoint == null || configuredEndpoint.trim().isEmpty()) {
            throw new IllegalArgumentException(
                "exporter.http.endpoint must be configured for the HTTP exporter"
            );
        }

        try {
            URI parsed = new URI(configuredEndpoint);
            String scheme = parsed.getScheme();
            if (
                scheme == null
                || (!"http".equalsIgnoreCase(scheme) && !"https".equalsIgnoreCase(scheme))
                || parsed.getHost() == null
            ) {
                throw new IllegalArgumentException(
                    "exporter.http.endpoint must be a valid HTTP or HTTPS URL"
                );
            }
            return parsed;
        } catch (URISyntaxException exception) {
            throw new IllegalArgumentException(
                "exporter.http.endpoint must be a valid HTTP or HTTPS URL",
                exception
            );
        }
    }

    private Map<String, String> validateHeaders(Map<String, String> configuredHeaders) {
        Map<String, String> validated = new LinkedHashMap<>();
        if (configuredHeaders == null) {
            return validated;
        }

        for (Map.Entry<String, String> header : configuredHeaders.entrySet()) {
            String name = header.getKey();
            String value = header.getValue();
            if (name == null || name.isBlank() || value == null) {
                throw new IllegalArgumentException(
                    "exporter.http.headers must be a mapping of non-blank string header names to string values"
                );
            }
            validated.put(name, value);
        }

        return Map.copyOf(validated);
    }
}
